import { COLORS } from "../../Theme/Colors";

export const EnergyData=[
    {
      id:1,
      BgImage:'https://agrinextcon.com/wp-content/uploads/2024/04/Anas.png',
      name:"Energy Evolution Awards, Conference & Expo",
      date:'13-15 March 2025',
      time:'09:00 AM TO 6:00 PM',
      Location:'Madrid Spain',
      City:'Spain',
      organizer:'Internetshine Technologies',
      TexT:'Energy Evolution Awards, Conference & Expo, a premier platform at the intersection of energy and technology. We are dedicated to recognizing and celebrating excellence in the energy technology sector, showcasing innovations, and fostering collaborations',
      companey:'organizer',
      CommonColor:COLORS.energyNext,
      Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
      webSite: 'https://radifarms.com/',
      email: 'khaled@radifarms.com',
      Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
      userName: 'Jim Marous',
    },
    {
       id:2,
       BgImage:'https://agrinextcon.com/wp-content/uploads/2024/04/Anas.png',
      name:"Energy Evolution Awards, Conference & Expo",
      date:'13-15 March 2025',
      time:'09:00 AM TO 6:00 PM',
      Location:'Madrid Spain',
      City:'Spain',
      organizer:'Internetshine Technologies',
      TexT:'Energy Evolution Awards, Conference & Expo, a premier platform at the intersection of energy and technology. We are dedicated to recognizing and celebrating excellence in the energy technology sector, showcasing innovations, and fostering collaborations',
      companey:'organizer',
      CommonColor:COLORS.energyNext,
      Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
      webSite: 'https://radifarms.com/',
      email: 'khaled@radifarms.com',
      Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
          userName: 'Jim Marous',
    },
  ]
  
  export const  Energyspeaker = [
    {
        id: 1,
        image2: 'https://energyevolutionexpo.com/wp-content/uploads/2024/05/Brais-Armino-Franco-420x420.jpg',
        name: 'Jim Marous',
        userName: 'Jim Marous',
        designation: 'Technoxian Founder',
        image3: require('../../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen: 'MyCalendar',
        BgImage:'https://agrinextcon.com/wp-content/uploads/2024/05/IMG_8827-scaled-1-2048x1366-min-1536x1025.jpg',
        Conferencename: "Finext Conference Moracco 2024",
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
    },
    {
        id: 2,
        image2: 'https://energyevolutionexpo.com/wp-content/uploads/2024/05/Ismail-Tekin-2-420x420.jpg',
        name: 'Brice Vandevoorde',
        designation: 'Technoxian Founder',
        userName: 'Brice Vandevoorde',
        image3: require('../../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen: 'MyCalendar',
        BgImage:'https://agrinextcon.com/wp-content/uploads/2024/05/IMG_8827-scaled-1-2048x1366-min-1536x1025.jpg',
        Conferencename: "Finext Conference Moracco 2024",
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
    },
    {
        id: 3,
        image2: 'https://energyevolutionexpo.com/wp-content/uploads/2024/05/Dr.-Agis-Digkas-420x420.jpg',
        name: 'Carole Alsharabati',
        designation: 'Technoxian Founder',
        userName: 'Carole Alsharabati',
        image3: require('../../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen: 'MyCalendar',
        BgImage:'https://agrinextcon.com/wp-content/uploads/2024/05/IMG_8827-scaled-1-2048x1366-min-1536x1025.jpg',
        Conferencename: "Finext Conference Moracco 2024",
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
    },
    {
        id: 4,
        image2: 'https://energyevolutionexpo.com/wp-content/uploads/2024/05/Ghada-RAHAL-420x420.jpg',
        name: 'Nameer-Khan',
        userName: 'Nameer-Khan',
        designation: 'Technoxian Founder',
        image3: require('../../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen: 'MyCalendar',
        BgImage:'https://agrinextcon.com/wp-content/uploads/2024/05/IMG_8827-scaled-1-2048x1366-min-1536x1025.jpg',
       
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
    },
    {
        id: 5,
        image2: 'https://energyevolutionexpo.com/wp-content/uploads/2024/05/Ronan-Carr-1-420x420.jpg',
        name: 'Georges Stephens',
        designation: 'Robotics Founder',
        image3: require('../../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        userName: 'Georges Stephens',
        screen: 'MyCalendar',
        BgImage:'https://agrinextcon.com/wp-content/uploads/2024/05/IMG_8827-scaled-1-2048x1366-min-1536x1025.jpg',
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
    },
    {
        id: 6,
        image2: 'https://energyevolutionexpo.com/wp-content/uploads/2024/06/WhatsApp-Image-2024-06-04-at-13.20.19-420x420.jpeg',
        name: 'Georges Stephens',
        designation: 'Robotics Founder',
        image3: require('../../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        userName: 'Georges Stephens',
        screen: 'MyCalendar',
        BgImage:'https://energyevolutionexpo.com/wp-content/uploads/2024/05/1-6.jpg',
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
    },
]
