import { COLORS } from "../Theme/Colors";

export const Mediadata = [
    {
        id: 1,
        image2: 'https://agrinextcon.com/wp-content/uploads/2024/02/FW-Magazine-1-150x150.png',
        name: 'khaleej Times',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
       
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },
    {
        id: 2,
        image2: 'https://agrinextcon.com/wp-content/uploads/2024/02/Untitled-1-1-150x150.jpg',
        name: 'Block Tides',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
       
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },

    {
        id: 3,
        image2: 'https://agrinextcon.com/wp-content/uploads/2024/02/gagran-logo-1.png',
        name: 'jagran News Media',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
      
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },
    {
        id: 4,
        image2: 'https://agrinextcon.com/wp-content/uploads/2024/02/Krishak-Jagat-1-150x150.png',
        name: 'Krishak Jagat',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
      
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },
    {
        id: 5,
        image2: 'https://agrinextcon.com/wp-content/uploads/2024/02/the-plate-1-1-150x150.png',
        name: 'The Plate',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
      
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },
    {
        id: 6,
        image2: 'https://agrinextcon.com/wp-content/uploads/2024/03/Agriculturetoday-150x150.jpg',
        name: 'Agriculture Today Group',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
      
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },

    {
        id: 7,
        image2: 'https://agrinextcon.com/wp-content/uploads/2024/02/biovoice-1-150x150.png',
        name: 'Bio Voice',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
     
        name: 'Ma Geelana',
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },
    {
        id: 8,
        image2: 'https://agrinextcon.com/wp-content/uploads/2024/02/image--150x150.jpg',
        name: 'FinanceWord MagaZine',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
       
        name: 'Ma Geelana',
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },
    {
        id: 9,
        image2: 'https://agrinextcon.com/wp-content/uploads/2024/02/Khaleej-Times-150x150.png',
        name: 'Startup News',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
     
        name: 'Ma Geelana',
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },
]
export const CompaneyData = [
    {
        id: 1,
         image2: 'https://agrinextcon.com/wp-content/uploads/2024/05/Elite-Agro-Projects.jpg',
        name: 'Elite Agro Projects',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
        // image2: "https://agrinextcon.com/wp-content/uploads/2024/01/1-4.jpg",
    
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },
    {
        id: 2,
        image2: 'https://agrinextcon.com/wp-content/uploads/2024/04/8OrbitLogo-scaled.jpg',
        name: 'Eight Orbit Urban Farms',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
       
     
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },
    {
        id: 3,
        image2: 'https://agrinextcon.com/wp-content/uploads/2024/03/Next-Business-Media.jpg',
        name: 'Next Business Media',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
     
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },
    {
        id: 4,
        image2: 'https://agrinextcon.com/wp-content/uploads/2024/03/A-banana-.jpg',
        name: 'A Banana Company',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
      
      
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },
    {
        id: 5,
        image2: 'https://agrinextcon.com/wp-content/uploads/2024/03/the-Smart-Farmers.jpg',
        name: 'The Smart Farmer',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
     
       
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },
    {
        id: 6,
        image2: 'https://agrinextcon.com/wp-content/uploads/2024/05/Elite-Agro-Projects.jpg',
        name: 'Elite Agro Projects',
        Location: 'Event Date',
        Date: '03-Oct-2023 \n 05-Oct-2023',
      
      
        designation: 'Co-Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen:'MyCalendar',
        BgImage:require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date:'25-26 September, 2024',
        time:'09:00 AM TO 6:00 PM',
        Location:'Marrakesh, Morocco',
        City:'Morocco',
        organizer:'Internetshine Technologies',
        TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey:'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },

]

export default Notifications = [
  {
    id: 1,
    title: 'Your pizza order placed successfully',
    details: 'Your pizza order to snack corner has been accepted and being processed.',
    image: require('../../Assets/Images/users/user-1.jpg')
  },
  {
    id: 2,
    title: 'Your bengali thali order has been delivered',
    details: 'Your bengali thali has been delivered by Delicious Bong Recipe.',
    image: require('../../Assets/Images/users/user-1.jpg')
  },
  {
    id: 3,
    title: 'Out for delivery',
    details: 'Bengali thali will reach to you within 30 minutes.',
    image: require('../../Assets/Images/users/user-1.jpg')
  },
  {
    id: 4,
    title: 'Your bengali thali order placed successfully',
    details: 'Your bengali thali order to Delicious Bong Recipe has been accepted and being processed.',
    image: require('../../Assets/Images/users/user-1.jpg')
  },
  {
    id: 5,
    title: 'Money added to your wallet',
    details: '₹ 1,000/- has been added to your wallet successfully and remaining balance is ₹ 1,150/-',
    image: require('../../Assets/Images/users/user-1.jpg')
  },
  {
    id: 6,
    title: 'Add money to your wallet',
    details: 'Only ₹ 150/- is left in your wallet. Add some more amount to place your order quickly.',
    image: require('../../Assets/Images/users/user-1.jpg')
  },
  {
    id: 7,
    title: 'Check new Pizza Corner within 1 km',
    details: 'A new Pizza Corner is being loved by more people around you.',
    image: require('../../Assets/Images/users/user-1.jpg')
  },
  {
    id: 8,
    title: 'Check new Roll Center within 3 km',
    details: 'A new roll center is being loved by more people around you.',
    image: require('../../Assets/Images/users/user-1.jpg')
  },
  {
    id: 9,
    title: 'Check new Crispy Chicken within 3 km',
    details: 'A new Crispy Chicken is being loved by more people around you.',
    image: require('../../Assets/Images/users/user-1.jpg')
  },
  {
    id: 10,
    title: 'Check new Snacks Corner within 5 km',
    details: 'A new Snacks Corner is being loved by more people around you.',
    image: require('../../Assets/Images/users/user-1.jpg')
  }
];
export const data = [
  {
    id: 1,
    image: require('../../Assets/Images/location.png'),
    Location: 'Venue Event',
    Date: 'Crowne Plaza\n Festival City Dubai',
    image2: 'https://agrinextcon.com/wp-content/uploads/2024/05/Danish.jpg',
    name: 'Dr. Danish',
    designation: 'Founder',
    image3: require('../../Assets/Images/google1.jpg'),
    name1: 'Microsoft',
    screen:'MapContainer',
    BgImage:require('../../Assets/Images/GirlImage.png'),
    Conferencename: "Finext Conference Moracco 2024",
    date:'25-26 September, 2024',
    time:'09:00 AM TO 6:00 PM',
    Location:'Marrakesh, Morocco',
    City:'Morocco',
    organizer:'Internetshine Technologies',
    TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
    companey:'organizer',
    Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
    webil: 'khaled@radifarms.com',
    Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
    useSite: 'https://radifarms.com/',
    emarName: 'Jim Marous',
    userName:"Dr. Fel De Su"
  },
  {
    id: 2,
    image: require('../../Assets/Images/calendar.png'),
    Location: 'Event Date',
    Date: '03-Oct-2023 \n 05-Oct-2023',
    image2: "https://agrinextcon.com/wp-content/uploads/2024/01/1-4.jpg",
    name: 'Ma Geelana',
    designation: 'Co-Founder',
    image3: require('../../Assets/Images/google1.jpg'),
    name1: 'facebook',
    screen:'MyCalendar',
    BgImage:require('../../Assets/Images/GirlImage.png'),
    Conferencename: "Finext Conference Moracco 2024",
    date:'25-26 September, 2024',
    time:'09:00 AM TO 6:00 PM',
    Location:'Marrakesh, Morocco',
    City:'Morocco',
    organizer:'Internetshine Technologies',
    TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
    companey:'organizer',
    Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
    webSite: 'https://radifarms.com/',
    email: 'khaled@radifarms.com',
    Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
    userName: 'Jim Marous',
  },
  {
    id: 3,
    image: require('../../Assets/Images/information.png'),
    Location: 'About Event',
    Date: 'The AgriNext\n Conference',
    image2: 'https://agrinextcon.com/wp-content/uploads/2024/01/1-5.jpg',
    name: 'Dr. Fel De Su',
    designation: 'Founder',
    image3: require('../../Assets/Images/google1.jpg'),
    name1: 'facebook',
    screen:'MyCalendar',
    BgImage:require('../../Assets/Images/GirlImage.png'),
    Conferencename: "Finext Conference Moracco 2024",
    date:'25-26 September, 2024',
    time:'09:00 AM TO 6:00 PM',
    Location:'Marrakesh, Morocco',
    City:'Morocco',
    organizer:'Internetshine Technologies',
    TexT:'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
    companey:'organizer',
    Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
    webSite: 'https://radifarms.com/',
    email: 'khaled@radifarms.com',
    Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
    userName: 'Jim Marous',
  },
 

  

];
