export const attendiesData = [
    {
        id: 1,
        image2: 'https://www.finextcon.com/wp-content/uploads/2023/07/6-2.png',
        name: 'Yasmine faike',
        designation: 'Technoxian Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen: 'MyCalendar',
        BgImage: require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',

    },
    {
        id: 2,
        image2: 'https://www.finextcon.com/wp-content/uploads/2023/07/1-2.png',
        name: 'Victer Tay',
        designation: 'Technoxian Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen: 'MyCalendar',
        BgImage: require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },
    {
        id: 3,
        image2: 'https://www.finextcon.com/wp-content/uploads/2023/07/FiNext-Awardee-Dubai-2023-1.png',
        name: 'Hemendra GHAGHADA',
        designation: 'Technoxian Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen: 'MyCalendar',
        BgImage: require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },
    {
        id: 4,
        image2: 'https://www.finextcon.com/wp-content/uploads/2023/07/8-1.png',
        name: 'Dr. Tamer Alsayed',
        designation: 'Technoxian Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen: 'MyCalendar',
        BgImage: require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },

    {
        id: 5,
        image2: 'https://www.finextcon.com/wp-content/uploads/2023/07/7-2.png',
        name: 'Jonathan Seifert',
        designation: 'Technoxian Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen: 'MyCalendar',
        BgImage: require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
        userName: 'Jim Marous',
    },


]
export const speakerData = [
    {
        id: 1,
        image2: 'https://www.finextcon.com/wp-content/uploads/2024/05/d1.jpg',
        name: 'Jim Marous',
        userName: 'Jim Marous',
        designation: 'Technoxian Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen: 'MyCalendar',
        BgImage: require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
    },
    {
        id: 2,
        image2: 'https://www.finextcon.com/wp-content/uploads/2023/07/Brice-Vandevoorde.png',
        name: 'Brice Vandevoorde',
        designation: 'Technoxian Founder',
        userName: 'Brice Vandevoorde',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen: 'MyCalendar',
        BgImage: require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
    },
    {
        id: 3,
        image2: 'https://www.finextcon.com/wp-content/uploads/2024/02/Carole-Alsharabati-Co-founder-Chairperson-CoorB.png',
        name: 'Carole Alsharabati',
        designation: 'Technoxian Founder',
        userName: 'Carole Alsharabati',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen: 'MyCalendar',
        BgImage: require('../../Assets/Images/GirlImage.png'),
        Conferencename: "Finext Conference Moracco 2024",
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
    },
    {
        id: 4,
        image2: 'https://www.finextcon.com/wp-content/uploads/2024/02/Nameer-Khan.png',
        name: 'Nameer-Khan',
        userName: 'Nameer-Khan',
        designation: 'Technoxian Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        screen: 'MyCalendar',
        BgImage: require('../../Assets/Images/GirlImage.png'),
       
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
    },
    {
        id: 5,
        image2: 'https://www.finextcon.com/wp-content/uploads/2024/02/george-1.png',
        name: 'Georges Stephens',
        designation: 'Robotics Founder',
        image3: require('../../Assets/Images/google1.jpg'),
        name1: 'facebook',
        userName: 'Georges Stephens',
        screen: 'MyCalendar',
        BgImage: require('../../Assets/Images/GirlImage.png'),
        date: '25-26 September, 2024',
        time: '09:00 AM TO 6:00 PM',
        Location: 'Marrakesh, Morocco',
        City: 'Morocco',
        organizer: 'Internetshine Technologies',
        TexT: 'FiNext Conference is owned and supported by InternetShine Corp, USA. The conference was created to provide a digital hub and meeting place for the global financial sector, allowing tech start-ups, SMEs, incumbent tech providers, investors, institutions, and other stakeholders to connect and interact under one roof',
        companey: 'organizer',
        Description: "Jim Marous, a visionary entrepreneur with a unique mix of experience combining business savvy with agriculture to provide closed-loop systems for sustainable supply chains and chemical-free production. Radi established a farm focused on raising high-quality livestock using sustainable practices which now nourishes a community seeking wholesome, all-natural products – Radi Farms. In addition, he has joined Mozare3 – the leading Agri-fintech startup in Cairo, Egypt as Chief Operations Officer to advance agriculture operations and food processing to introduce high-quality local production for different buyers and better income & employment opportunities for the agriculture sector. Radi is keen on supporting technology adoption and financial inclusion across the supply chain to enhance farmers’ experience and their income.",
        webSite: 'https://radifarms.com/',
        email: 'khaled@radifarms.com',
        Linkdin: 'https://www.linkedin.com/company/agrinextcon/',
    },
]